-- AlterTable
ALTER TABLE "Note" ADD COLUMN "width" REAL NOT NULL DEFAULT 256;
ALTER TABLE "Note" ADD COLUMN "height" REAL NOT NULL DEFAULT 180;
ALTER TABLE "Note" ADD COLUMN "fontSize" REAL NOT NULL DEFAULT 16;
